Yubico/Yubico.NET.SDK

Yubico.NativeShims/msbuild/Yubico.NativeShims.targets
This fixes an issue that causes the wrong Yubio.NativeShims.dll to be used. If a user uses the 'AnyCPU' platform target, this issue could potentially result in users mixing 32-bit and 64-bit dlls and leave users with errors such as 'BadImageFormatException' whenever code that utilizes the Yubico SDK was called.
AnyCPU shouldn't default to x86 unless the architecture of the host machine performing a build is also x86.
AnyCPU can also utilize x64 architecture, and is supposed to only fallback to x86 if x64 isn't possible.
Defaulting to either option can potentially result in bitness mismatches
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#platformtarget
=> Update MSBuild DLL import conditions

Yubico.NativeShims/CMakeLists.txt
  Added /cf parameter to Windows build (change in CMakelists.txt) to enable Control Flow Guard in Yubico.Nativeshims project.
  There is no known vulnerability in the Yubico SDK that drives this change; it is simply a best practice for code that interacts with unsafe functions to adopt all available platform security measures for native code. This change may enable high security environments to proactively protect against unknown future vulnerabilities found in code that interacts with memory unsafe functions.
Control Flow Guard (CFG) is a robust security feature designed to counter memory corruption vulnerabilities by imposing strict limitations on code execution within an application. It significantly reduces the risk of exploits, particularly those exploiting vulnerabilities like …
=> Enable Control Flow Guard for Windows Build

Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/EcdsaVerify.cs
Certificate OID friendly name is not cross-platform. The certificate on
Windows is of type ECDsaCng while on Ubuntu it is of type ECDsaOpenSsl.
This causes the friendly names to differ, where it's `nistP256` with
ECDsaCng and `ECDSA_P256` with ECDsaOpenSsl. The OID value is the same
with both.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test configuration**: Encountered when running MakeCredential on a Linux machine. You can verify the friendly name issue with the following code snippet:
```csharp
// Certificate was copied from a MakeCredential call, it is an attestation certificate.
var cert = new …
```
=> Fix EcdsaVerify.CheckECDsa when cert is OpenSSL

Yubico.Core/src/Yubico/Core/CoreCompatSwitches.cs, Yubico.Core/src/Yubico/Core/Devices/SmartCard/DesktopSmartCardDevice.cs
Reverts the change in behavior to open smart card handles exclusively. Instead now defaults back to shared like it was before, but allows for applications to toggle between the new and old behavior through the use of `AppContext.SetSwitch`.
Fixes #72 and probably #81 as well.
Wrote some test code using the TestApp and verified:
- No compat flag present = SHARED
- Flag present & false = SHARED
- Flag present & true = EXCLUSIVE
* Firmware version: 5.4.3
* Yubikey model: ANFC
=> Default back to old SCardConnect behavior

Yubico.Core/src/Yubico/Core/Devices/Hid/MacOSHidIOReportConnection.cs, Yubico.Core/src/Yubico/PlatformInterop/macOS/IOKitFramework/IOKitHidConstants.cs
This has been a longstanding bug in the SDK that has been haunting me since the FIDO device code was originally written. Apple's documentation on how async input reports are intended to work are about as clear as mud. But with some extra (temporary) debug logging I was able to finally reproduce the issue with enough visibility into what was actually happening. The implementation used by our own `libfido2` library now makes a lot more sense as well.
Fundamentally, we were just using the `IOHIDDeviceRegisterInputReportCallback` and its corresponding callback incorrectly. The read buffer that we supply during the registration is just meant to be a place for macOS to cache the report data... I guess? The intended use still is not super clear to me.
But what was clear from the logs is that the …
=> Queue macOS input reports so that large responses aren't dropped

Yubico.NET.SDK.sln, Yubico.YubiKey/docs/users-manual/sdk-programming-guide/appcompat.md, Yubico.YubiKey/src/Yubico/YubiKey/FirmwareVersion.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyCompatSwitches.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyDevice.Instance.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyFeature.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyFeatureExtensions.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/ReclaimTimeoutTests.cs
The reclaim timeout was introduced in the YubiKey NEO. Because the NEO used a separate chip for USB communication from the secure element, there was a delay that was needed for stability reasons whenever the host (computer) wanted to switch USB interfaces. This interface "reclaim" timeout was a whopping 3 seconds - meaning if you wanted to switch from talking to OTP to FIDO, you needed to wait 3 seconds prior to issuing the first FIDO command.
Even though it was no longer needed in the YubiKey 4/5 hardware platform, this reclaim timeout behavior was ported over. After some discussions with the firmware team, they agreed that this timeout was no longer needed and could be removed. This "fast reclaim" was merged into FW 5.6.0 and is available in all subsequent versions.
This PR adds a …
=> Fast USB interface reclaim

Yubico.YubiKey/tests/unit/Yubico/YubiKey/TestUtilities/IntegrationTestDeviceEnumerationTests.cs, Yubico.YubiKey/tests/utilities/Yubico/YubiKey/TestUtilities/IntegrationTestDeviceEnumeration.cs
The tests wouldn't pass consistently, so this adds a small delay for the IO and more reliable paths
Fixes: develop
=> More reliable paths/IO for IntegrationTestDeviceEnumeration

Yubico.YubiKey/docs/users-manual/application-piv/pin-puk-mgmt-key.md
Fixed typo and sentence clarity (requested by Fiona).
=> fixed typo, clarity

.editorconfig, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.Pinonly.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/ManagementKeyTests.cs
This fix addresses a situation in which the `ManagementKeyAlgorithm` used to authenticate to the Yubikey could be wrong after an Piv application reset, by updating the `ManagementKeyAlgorithm` on reset.
Fixes # YESDK-1342
Added integrationtests 
* Firmware version: 5.7, 5.4.3
* Yubikey model: YK5, USBA
=> Fix: Update ManagementKeyAlgorithm on PIV Application reset

.github/workflows/check-code-formatting.yml, .github/workflows/verify-code-style.yml, Yubico.NET.SDK.sln
This adds dotnet to the path for the often failing code format action. This fix was suggested by GitHub themselves.
Fixes # YESDK-1338
Successfully passed three times consecutively in this PR which looks promising.
N/A
=> Fix: Add dotnet to path for failing verify-code-style GitHub Action

Yubico.YubiKey/docs/users-manual/application-piv/apdu/bio-metadata.md, Yubico.YubiKey/docs/users-manual/application-piv/apdu/verify-temporary-pin.md, Yubico.YubiKey/docs/users-manual/application-piv/apdu/verify-uv.md, Yubico.YubiKey/docs/users-manual/application-piv/commands.md, Yubico.YubiKey/src/Resources/ExceptionMessages.Designer.cs, Yubico.YubiKey/src/Resources/ExceptionMessages.resx, Yubico.YubiKey/src/Resources/ResponseStatusMessages.Designer.cs, Yubico.YubiKey/src/Resources/ResponseStatusMessages.resx, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/GetBioMetadataCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/GetBioMetadataResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyTemporaryPinCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyTemporaryPinResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyUvCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyUvResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivBioMetadata.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivPinPolicy.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/BioMultiProtocolTests.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/PinBioMultiProtocolTests.cs
Adds Metadata and Verify extensions for YubiKey Bio MPE.
Adds new slot verification policies (PIN_OR_MATCH_ONCE and PIN_OR_MATCH_ALWAYS).
There are new integration tests for verifying that we receive expected data.
* Firmware version: 5.6+
* Yubikey model: YK Bio MPE
=> Add PIV Bio extensions

Yubico.Core/tests/Yubico.Core.UnitTests.csproj, Yubico.Core/tests/Yubico/Core/Cryptography/AesGcmPrimitivesOpenSslTests.cs, Yubico.YubiKey/src/Yubico/YubiKey/IYubiKeyDevice.cs, Yubico.YubiKey/src/Yubico/YubiKey/Management/Commands/DeviceResetCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Management/Commands/DeviceResetResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyDevice.Instance.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyFeature.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyFeatureExtensions.cs, Yubico.YubiKey/tests/utilities/Yubico/YubiKey/TestUtilities/HollowYubiKeyDevice.cs
Adds command for device reset
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Firmware version:
* Yubikey model:
=> Add device reset command

.editorconfig, Yubico.YubiKey/docs/users-manual/sdk-programming-guide/pin-complexity-policy.md, Yubico.YubiKey/docs/users-manual/toc.yml, Yubico.YubiKey/examples/Fido2SampleCode/KeyCollector/Fido2SampleKeyCollector.cs, Yubico.YubiKey/examples/PivSampleCode/KeyCollector/SampleKeyCollector.cs, Yubico.YubiKey/src/Resources/ExceptionMessages.Designer.cs, Yubico.YubiKey/src/Resources/ExceptionMessages.resx, Yubico.YubiKey/src/Resources/ResponseStatusMessages.Designer.cs, Yubico.YubiKey/src/Resources/ResponseStatusMessages.resx, Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Commands/Fido2Response.cs, Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Fido2Exception.cs, Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Fido2Session.Pin.cs, Yubico.YubiKey/src/Yubico/YubiKey/KeyEntryData.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/ChangeReferenceDataResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/ResetRetryResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.Pin.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/PinComplexityTests.cs
Fw 5.7 adds PIN complexity. With this change the clients can in unified way catch `SecurityException` from PIV ChangePin/Puk and FIDO2s Set/ChangePin methods.
Fixes # YESDK-1378
Added integration tests, tested with device which have PIN complexity enabled. Updated PIV and Fido2 sample applications to handle PIN complexity policy violations.
=> Additions for PIN complexity violation

.editorconfig, .github/ISSUE_TEMPLATE/2-bug-report.yml, .github/workflows/verify-code-style.yml, Yubico.NativeShims/CMakeLists.txt, Yubico.NativeShims/vcpkg.json, Yubico.YubiKey/docs/users-manual/getting-started/whats-new.md, Yubico.YubiKey/docs/users-manual/sdk-programming-guide/pin-complexity-policy.md, Yubico.YubiKey/docs/users-manual/toc.yml, Yubico.YubiKey/examples/Fido2SampleCode/KeyCollector/Fido2SampleKeyCollector.cs, Yubico.YubiKey/examples/PivSampleCode/KeyCollector/SampleKeyCollector.cs, Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Fido2Session.Pin.cs, Yubico.YubiKey/src/Yubico/YubiKey/KeyEntryData.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/ChangeReferenceDataResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/ResetRetryResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyUvCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.Pin.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/DeviceResetTests.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/PinComplexityTests.cs, build/Versions.props
This merges the changes from the 1.11 release into the develop branch.
Release date: June 28th, 2024
This release introduces significant enhancements and new features for the latest YubiKeys, including support for
firmware version 5.7, which allows for temporary disabling of NFC connectivity and checking PIN complexity status.
It also expands RSA key support in PIV to 3072 and 4096-bit keys, and includes improvements for YubiKey Bio and
Multi-Protocol Edition keys.
Additionally, there are optimizations in USB reclaim speed and adjustments to the touch sensor sensitivity and a few bug
fixes.
Several command classes have been deprecated due to changes in how device info is read by the SDK, and integration test
guardrails have been implemented for better security.
Features:
- Support for …
=> Release 1.11.0

.github/workflows/build-nativeshims.yml, Yubico.NativeShims/vcpkg.json
The schema has not been updated for a while and its url has been moved.
See following links:
1. https://github.com/microsoft/vcpkg/issues/28366
2. https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json
=> Fix: Update vcpkg schema

Yubico.YubiKey/src/Yubico/YubiKey/Management/Commands/SetDeviceInfoBaseCommand.cs
Apparently, when this property was added, it wasn't added to the copy constructor.
Fixes # [YESDK-1344](https://yubico.atlassian.net/browse/YESDK-1344)
Currently testing by PFS QA team running PCS for FIDO Prereg testing
* Firmware version: 5.7.1
* Yubikey model: ANFC/CNFC
=> Adding TemporaryTouchThreshold to the copy constructor

Yubico.YubiKey/docs/users-manual/application-piv/apdu/bio-metadata.md, Yubico.YubiKey/docs/users-manual/application-piv/apdu/verify-uv.md, Yubico.YubiKey/docs/users-manual/application-piv/apdu/verify.md, Yubico.YubiKey/docs/users-manual/application-piv/commands.md, Yubico.YubiKey/docs/users-manual/application-piv/pin-touch-policies.md, Yubico.YubiKey/docs/users-manual/getting-started/whats-new.md, Yubico.YubiKey/docs/users-manual/sdk-programming-guide/pin-complexity-policy.md, Yubico.YubiKey/docs/users-manual/sdk-programming-guide/sensitive-data.md, Yubico.YubiKey/docs/users-manual/toc.yml, Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Commands/ResetCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/IYubiKeyDevice.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/DeleteKeyCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/DeleteKeyResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/GetBioMetadataCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/GetBioMetadataResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/MoveKeyCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/MoveKeyResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyTemporaryPinResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyUvCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/VerifyUvResponse.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyFeature.cs
Documentation updates for release 1.11.
API doc (.cs) and user's manual doc (.md and .yml) updates.
Built docs locally.
=> Documentation updates for release 1.11.

Yubico.YubiKey/src/Yubico/YubiKey/Fido2/MakeCredentialParameters.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Fido2/MakeCredentialGetAssertionTests.cs
[The CTAP spec](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#sctn-credProtect-extension) defines two input parameters for the client-side part of the credProtect extension, credentialProtectionPolicy and enforceCredentialProtectionPolicy. MakeCredentialParameters.AddCredProtectExtension already supports handling the credentialProtectionPolicy parameter, but it does not support the enforceCredentialProtectionPolicy parameter. This means that callers who want to properly support enforceCredentialProtectionPolicy would need to do their own checks against the keys' support levels and the requested policy so as not to return an error when enforceCredProtectPolicy is false, and in doing so would end up duplicating most of …
=> Add support for enforceCredProtectPolicy in AddCredProtectExtension

Yubico.YubiKey/tests/integration/Yubico/YubiKey/Fido2/Commands/EnumCredsCommandTests.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Fido2/Commands/EnumRpsCommandTests.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Fido2/Commands/UpdateUserInfoCommandTests.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Fido2/SimpleCredMgmtTests.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Management/SetDeviceInfoCommandTests.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/PinComplexityTests.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/ReclaimTimeoutTests.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/U2f/PinTests.cs, Yubico.YubiKey/tests/utilities/Yubico/YubiKey/TestUtilities/TestCategories.cs
- Removed test categories
- Set appropriate test categories 
- Add static keyword
=> Minor test categorizing

.editorconfig
Removing crlf from .editorconfig, this will make it so that dotnet format doesn't attempt to fix line endings when this is being handled by Git (with Windows: autocrlf=true, Linux/Mac: input)
=> Remove crlf from .editorconfig

Yubico.Core/src/Yubico/Core/Devices/DeviceEventArgs.cs, Yubico.Core/src/Yubico/Core/Devices/Hid/HidDeviceEventArgs.cs, Yubico.Core/src/Yubico/Core/Devices/Hid/HidDeviceListener.cs, Yubico.Core/src/Yubico/Core/Devices/Hid/MacOSHidDeviceListener.cs, Yubico.Core/src/Yubico/Core/Devices/Hid/NullDevice.cs, Yubico.Core/src/Yubico/Core/Devices/Hid/WindowsHidDeviceListener.cs, Yubico.Core/src/Yubico/Core/Devices/SmartCard/SmartCardDeviceEventArgs.cs, Yubico.Core/tests/Yubico/Core/Devices/Hid/HidTranslatorTests.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyDevice.Static.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyDeviceListener.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/YubiKeyTests.cs
Currently, YubiKeyDeviceListener only exposes a singleton instance with no way for a consumer to reset it once it is started. The constructor is private, so the consumer has no option to use a private instance.
This adds the ability for the consumer to reset the lazy-initialized singleton so that the listen thread doesn't stick around.
Also, even though this class implemented IDisposable, most things that need to be in the Dispose method weren't there, including a way to stop the thread.
The listen thread is now replaced by an asynchronous task that doesn't consume a system thread while it's not working.
Fixes # YESDK-1313
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list …
=> Make YubiKeyDeviceListener resettable

Yubico.Core/src/Yubico/PlatformInterop/Windows/Cfgmgr32/CmDevice.cs
Adds the name of the key that was missing in the dictionary to the thrown exception
=> Add name of property to exception

build/sign.ps1
This PR introduces a PowerShell script (`sign.ps1`) that automates the process of signing NuGet and Symbol packages using a hardware-based certificate. The script streamlines the release signing workflow by handling package extraction, assembly signing, repackaging, and final package signing in a single operation.
- Signs assemblies within NuGet packages using a smart card certificate
- Processes both NuGet (*.nupkg) and Symbol (*.snupkg) packages
- Supports custom paths for signtool.exe and nuget.exe
- Configurable timestamp server
- Optional cleanup of working directories
- Comprehensive error handling and logging
- PowerShell 5.1 or later
- Smart card with signing certificate
- Windows SDK (signtool.exe)
- NuGet CLI (nuget.exe)
```powershell
Invoke-NuGetPackageSigning -Thumbprint …
```
=> ci: added a signing script to sign build assets

build/sign.ps1
fixed bug where the script attempted to veryfy the zips and not the nupkgs inside.
=> ci: fixed bug in sign.ps1

README.md, Yubico.Core/src/Yubico.Core.csproj, Yubico.DotNetPolyfills/src/Yubico.DotNetPolyfills.csproj, Yubico.YubiKey/src/Yubico.YubiKey.csproj
Now including README.md in the NuGet packages, which creates a better first impression of the project.
Here are the key changes made to improve the README.md:
Table of Contents
- Fixed anchor links by using GitHub-compatible formatting
- Added nested structure for better navigation
- Added missing sections
Content Organization
- Added Basic Usage section with practical code example
- Streamlined the introduction
- Removed redundant content
Formatting
- Added emoji icons for better visual hierarchy
- Consistent heading levels
- Clean spacing and indentation
Structure
- Added clear sections for Installation and Basic Usage
- Simplified the Security section
- Added direct issue creation link
Removed
- Redundant documentation explanations
- Extra whitespace
- Unnecessary technical details
The …
=> Including README.md in the NuGet Packages

build/sign.ps1
improvements to sign output:
╰─ $ Invoke-NuGetPackageSigning -WorkingDirectory 1.12 -Thumbprint $thumbprint
Initializing NuGet package signing process...
Verifying required tools...
✓ SignTool found at: signtool.exe
✓ NuGet found at: nuget.exe
✓ GitHub CLI  found at: nuget.exe
Certificate Details:
Subject:      CN=Yubico AB, O=Yubico AB, L=STOCKHOLM, S=Stockholms län, C=SE
Issuer:       CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1, O="DigiCert, Inc.", C=US
Thumbprint:   A1614CD84976030D49209B56162D9EFA69B73698
Valid From:   02/27/2024 01:00:00
Valid To:     02/27/2027 00:59:59
Creating directory structure...
Validating required build assets...
:white_check_mark: Found Symbol packages in: Symbols Packages.zip
:white_check_mark: Found NuGet packages in: Nuget Packages.zip …
=> ci: improvements to sign output

Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/InitializeAuthenticateManagementKeyCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/SetManagementKeyCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.Pinonly.cs
Documentation updates for changes in https://github.com/Yubico/Yubico.NET.SDK/pull/167.
=> documentation: management key algorithm 

Yubico.YubiKey/src/Yubico/YubiKey/ConnectionFactory.cs, Yubico.YubiKey/src/Yubico/YubiKey/Oath/OathSession.cs
The ConnectionFactory incorrectly selected the SmartCardConnection instead of the FIDO2Connection
Fixes: #178
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* OS version: *e.g. Windows 11*
* Firmware version: 5.4.3 and 5.7.2 keys
* Yubikey model[^1]: 
[^1]: See [Yubikey models](https://www.yubico.com/products/) (Multi-protocol, Security Key, FIPS, Bio, YubiHSM, YubiHSM FIPS)
=> fix: ConnectionFactory incorrectly using SmartCardConnection

README.md, Yubico.Core/src/Yubico.Core.csproj, Yubico.DotNetPolyfills/src/Yubico.DotNetPolyfills.csproj, Yubico.YubiKey/docs/users-manual/getting-started/whats-new.md, Yubico.YubiKey/src/Yubico.YubiKey.csproj, Yubico.YubiKey/src/Yubico/YubiKey/ConnectionFactory.cs, Yubico.YubiKey/src/Yubico/YubiKey/Oath/OathSession.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/InitializeAuthenticateManagementKeyCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/Commands/SetManagementKeyCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Piv/PivSession.Pinonly.cs, build/Versions.props, build/sign.ps1
Patch release: 1.12.1
Release date: December 19th, 2024
Bug Fixes: Now selects correct device initializing Fido2Session [(#179)](https://github.com/Yubico/Yubico.NET.SDK/pull/179)
=> Release 1.12.1

.github/workflows/build-nativeshims.yml
This will fix failing runs due to no version specified (which only happens when user triggers build). I.e., the cron jobs will continue to work.
=> ci: only package artifacts on manual trigger (nativeshims)

.github/workflows/build-nativeshims.yml, Yubico.NativeShims/build-linux-amd64.sh, Yubico.NativeShims/build-linux-arm64.sh
This upgrades the ubuntu runners from 20.04 to 22.04 which allow for the compilation of Yubico.NativeShims.
=> Upgrade Ubuntu runners from 20.04 to 22.04

Yubico.YubiKey/docs/users-manual/toc.yml
Added missing file (appcompat.md) to the toc.
Local docs build
=> Adding Appcompat.md to toc.tml for visibility on the documentation site

LICENSE.txt
This pull request includes a change to the `LICENSE.txt` file. The change involves removing the license information for the `AesCmac.cs` file from the Bouncy Castle library.
(Since we are now using using OpenSSL and CryptographicProviders, removed in [3f2d52a](https://github.com/Yubico/Yubico.NET.SDK/commit/3f2d52a6d6d505e051de9e6dcce174dba64892db))
License information removal:
* [`LICENSE.txt`](diffhunk://#diff-d0ed4cc3fb70489fe51c7e0ac180cba2a7472124f9f9e9ae67b01a37fbd580b7L263-L275): Removed the license information for `Yubico.YubiKey\src\Yubico\YubiKey\Cryptography\AesCmac.cs`, which was previously included under the Bouncy Castle license.
=> misc: Removed Bouncy Castle license

Yubico.YubiKey/src/Yubico/YubiKey/ConnectionFactory.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/ReclaimTimeoutTests.cs
There is a 100ms/3s delay on the first connection. The change is in waitForReclaimTimeout, Possible fix is to change the early-return check from in ConnectionFactory.cs, line 158.
```
if (_device.LastActiveTransport == newTransport )
to
if (_device.LastActiveTransport == newTransport || _device.LastActiveTransport == Transport.None)
{
_device.LastActiveTransport = newTransport;
return;
}
```
Inside the if statement, _device.LastActiveTransport is updated to prevent it from remaining None indefinitely, which could lead to unexpected transport behavior.
Activity
Fixes: # <[YESDK-1432](https://yubico.atlassian.net/jira/software/c/projects/YESDK/issues/YESDK-1432?jql=project%20%3D%20%22YESDK%22%20ORDER%20BY%20created%20DESC)>
The test case public void …
=> Skip waiting for the first connection to the key

README.md
This pull request includes updates to the `README.md` file to add a new section on build asset attestation. The most important changes are:
Documentation updates:
* Added a new section titled "Build asset attestation" to the `README.md` file. This section provides information on how to verify that the NuGet package has been generated from the repository using GitHub Attestations.
* Updated the table of contents in the `README.md` file to include a link to the new "Build asset attestation" section.
=> docs: add section on build asset attestation to README

.github/scripts/commit-and-push.sh, .github/scripts/configure-git-pgp.sh, .github/scripts/wait-for-commit-status.sh, .github/workflows/deploy-docs.yml
Add a workflow to update the yesdk deployment of the docs-gitops repo with a specified image tag.
=> Add workflow to automate deployment of docs

Yubico.YubiKey/src/Yubico/YubiKey/Pipelines/CommandChainingTransform.cs, Yubico.YubiKey/src/Yubico/YubiKey/SmartCardConnection.cs, Yubico.YubiKey/src/Yubico/YubiKey/SmartCardMaxApduSizes.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/Commands/PutDataCommandTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Pipelines/CommandChainingTransformTests.cs
This PR stops sending data to the YubiKey after it has exceeded the max allowed APDU size. 
Previously, the SDK would hammer the YubiKey until it had emptied its buffer.
It also adds the MaxApduSize constants.
The valid sizes (in bytes) for the smartcard connection on the YubiKey are as follows
NEO: 1390 
YK4: 2038 
YK4_3 : 3062
Fixes: YESDK-1329
Added unit tests in SmartCardTransformTests.cs
* OS version: Arch Linux
* Firmware version: 5.4.3
* Yubikey model[^1]: 5 USBA
[^1]: See [Yubikey models](https://www.yubico.com/products/) (Multi-protocol, Security Key, FIPS, Bio, YubiHSM, YubiHSM FIPS)
=> fix: Stop send short APDUs when exceeded max APDU size

Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Commands/BioEnrollmentCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Commands/ConfigCommand.cs, Yubico.YubiKey/src/Yubico/YubiKey/Fido2/Commands/CredentialManagementCommand.cs
See https://www.yubico.com/support/security-advisories/ysa-2025-02/. FW versions before 5.7.4 were only requiring the first 16 bytes of the fido2 pinUvAuthToken when using protocol 2, but should have been requiring the full 32 bytes. Several commands in the SDK were truncating the auth token to 16 bytes before passing it to these commands. The firmware bug has been fixed in 5.7.4 and so any fido2 commands that require a pinUvAuthToken now require the full 32 bytes under protocol 2. Since the SDK is only sending 16 bytes for several commands, they fail with CTAP2_ERR_PIN_AUTH_INVALID on 5.7.4+. 
Tested with several of the existing integration tests
* BioEnrollmentCommandTests (some) with a 5.7.1 BIO A MPE
* ConfigCommandTests (some) and EnumCredsCommandTests, with a 5.7.4 C NFC and a 5.7.1 …
=> fix: Remove incorrect auth token truncation from various commands

.github/ISSUE_TEMPLATE/2-bug-report.yml, .github/ISSUE_TEMPLATE/3-feature-request.yml
This pull request updates the issue templates in the `.github/ISSUE_TEMPLATE` directory to include a `type` field for better categorization of issues.
Enhancements to issue templates:
* [`.github/ISSUE_TEMPLATE/2-bug-report.yml`](diffhunk://#diff-7b1d4ddf04b840c3e0192aaf577d0113bfad655091af7c7ac114f72d0d3f3098R5): Added a `type: Bug` field to the bug report template to explicitly categorize it as a bug.
* [`.github/ISSUE_TEMPLATE/3-feature-request.yml`](diffhunk://#diff-5aa1e77f2707b998783cd4ec258dd9e923d7f90b436bcd332c01860cce21b880R5): Added a `type: Feature` field to the feature request template to explicitly categorize it as a feature.
=> github: Add issue type to GitHub issue template

Yubico.YubiKey/src/Yubico/YubiKey/FirmwareVersion.cs, Yubico.YubiKey/src/Yubico/YubiKey/VersionQualifier.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubiKeyDeviceInfo.cs, Yubico.YubiKey/src/Yubico/YubiKey/YubikeyDeviceManagementTags.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/VersionQualifierTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/YubikeyDeviceInfoTests.cs
This pull request introduces several enhancements and new features to the `Yubico.YubiKey` library, focusing on firmware version handling, version qualifiers, and unit tests. The most important changes include adding a `VersionQualifier` class, updating `YubiKeyDeviceInfo` to support version qualifiers, and introducing comprehensive unit tests for these updates.
Fixes: YESDK-1451
I have ran unit tests similar to those in the Java Yubikit SDK. I have yet to run them on actual keys.
* OS version: Linux
* Firmware version: N/A
* Yubikey model[^1]: N/A
[^1]: See [Yubikey models](https://www.yubico.com/products/) (Multi-protocol, Security Key, FIPS, Bio, YubiHSM, YubiHSM FIPS)
* **New method to parse firmware versions from byte arrays:** Added …
=> feat: Implement reading of VersionQualifier into YubikeyDeviceInfo

.github/dependabot.yml
This pull request introduces a new `.github/dependabot.yml` configuration file to automate dependency updates for the project. The configuration specifies two package ecosystems (`nuget` and `dotnet-sdk`) with distinct update rules and schedules.
* Configured updates for the `nuget` ecosystem:
- Scheduled weekly updates on Wednesdays at 09:00 (Europe/Stockholm timezone).
- Grouped updates for all packages, limited to minor and patch updates, with a maximum of 10 open pull requests.
* Configured updates for the `dotnet-sdk` ecosystem:
- Scheduled weekly updates on Wednesdays at 09:00 (Europe/Stockholm timezone).
- Ignored major version updates for all dependencies.
=> ci: Add dependabot scanning for dependency updates 

Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/AsnPrivateKeyDecoder.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/AsnPublicKeyDecoder.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/Curve25519PrivateKey.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/Curve25519PublicKey.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/ECPrivateKey.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/ECPublicKey.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/IKeyBase.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/IPrivateKey.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/IPrivateKeyExtensions.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/IPublicKey.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/PrivateKey.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/PublicKey.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/RSAPrivateKey.cs, Yubico.YubiKey/src/Yubico/YubiKey/Cryptography/RSAPublicKey.cs, Yubico.YubiKey/tests/integration/Yubico/YubiKey/Piv/KeyAgreeTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Cryptography/Curve25519PublicKeyTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Cryptography/ECPublicKeyTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Cryptography/RSAPublicKeyTests.cs, Yubico.YubiKey/tests/utilities/Yubico/YubiKey/TestUtilities/TestKey.cs, Yubico.YubiKey/tests/utilities/Yubico/YubiKey/TestUtilities/TestKeyExtensions.cs, docs/users-manual/application-piv/private-keys.md, docs/users-manual/application-u2f/u2f-commands.md, docs/users-manual/getting-started/whats-new.md, docs/users-manual/sdk-programming-guide/secure-channel-protocol.md
This pull request introduces several enhancements and refactorings to the cryptographic key classes in the `Yubico.YubiKey` library. The changes focus on improving code clarity, adding comprehensive documentation, and modernizing factory methods for creating key instances. Below are the most important changes grouped by theme.
* Added detailed XML documentation to most cryptographic key classes and interfaces, such as `Curve25519PrivateKey`, `Curve25519PublicKey`, `ECPrivateKey`, `ECPublicKey`, `RSAPrivateKey`, and `RSAPublicKey`. These updates include class summaries, remarks, and examples for better understanding of their purpose and usage. [[1]](diffhunk://#diff-5e98fb4c37622f7d40738ff80ed8fb4bef27fe6e9987e2943d06424abc58d478R20-R27) …
=> refactor: Add consistent docs and proper naming for certain methods for creating keys

.github/workflows/build.yml, .github/workflows/upload-docs.yml
This pull request updates the GitHub Actions workflows to enhance artifact handling and build summaries. Key improvements include adding outputs for artifact IDs, refining artifact links in the build summary, and introducing additional outputs for Docker image metadata.
* Added outputs in `.github/workflows/build.yml` to capture artifact IDs for documentation logs, documentation, NuGet packages, symbols packages, and assemblies. These IDs are used to generate direct artifact links in the build summary.
* Assigned unique `id` values to artifact upload steps (`docs-log-upload`, `docs-upload`, `nuget-upload`, `symbols-upload`, `assemblies-upload`) for better integration with outputs. [[1]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R109) …
=> ci: fix links for build output and add image hash

Yubico.Core/tests/Yubico.Core.UnitTests.csproj, Yubico.Core/tests/Yubico/Core/Devices/Hid/HidConnectionTests.cs, Yubico.Core/tests/Yubico/Core/Logging/LogTests.cs, Yubico.YubiKey/src/Yubico/YubiKey/Pipelines/ScpApduTransform.cs, Yubico.YubiKey/tests/unit/Yubico.YubiKey.UnitTests.csproj, Yubico.YubiKey/tests/unit/Yubico/YubiKey/ConnectionManagerTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Fido2/Fido2SessionTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Pipelines/CommandChainingTransformTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Pipelines/OathResponseChainingTransformTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Pipelines/ResponseChainingTransformTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Pipelines/ScpApduTransformTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Pipelines/SmartCardTransformTests.cs, Yubico.YubiKey/tests/unit/Yubico/YubiKey/Scp/Scp03StateTests.cs, Yubico.YubiKey/tests/utilities/Yubico/YubiKey/TestUtilities/TestDeviceSelection.cs
This pull request updates unit tests across multiple files to replace the `Moq` mocking library with `NSubstitute`. 
* [`Yubico.Core/tests/Yubico.Core.UnitTests.csproj`](diffhunk://#diff-ee808297e9f4a1c86785fc217491dc426cb1538b78550a01be1923c227873ec9R46-L52): Removed the `Moq` package and added the `NSubstitute` package (`Version 5.3.0`).
* [`Yubico.YubiKey/tests/unit/Yubico.YubiKey.UnitTests.csproj`](diffhunk://#diff-996dd45b63b3c63719489920cef0d8f3c96667e9fab09a15337163447a12288dR34-L40): Similar updates as above, replacing `Moq` with `NSubstitute`.
* [`Yubico.Core/tests/Yubico/Core/Devices/Hid/HidConnectionTests.cs`](diffhunk://#diff-ca49e7dc62a03edf6718044e52d4496d2dac5a240887dc3401a89148f728af83L23-R49): Replaced `Moq` mocks with `NSubstitute` substitutes for `IHidDDevice`. Updated …
=> Replace Moq with NSubstitute

Yubico.NativeShims/vcpkg.json, build/Versions.props, docs/users-manual/getting-started/whats-new.md
Original release: #259 
On top of the original release, this PR adds: #261
=> Release/1.13.2 - Update

Yubico.Core/src/Yubico.Core.csproj, Yubico.YubiKey/src/Yubico.YubiKey.csproj, build/Attribution.props
This pull request introduces updates to NuGet package metadata and repository-wide attribution settings to improve clarity, consistency, and compliance. The most important changes include adding `PackageId` and `PackageTags` fields to `.csproj` files, updating the copyright information dynamically, and reorganizing metadata for better readability.
* `Yubico.Core.csproj` and `Yubico.YubiKey.csproj`: Added `PackageId` and `PackageTags` fields to enhance discoverability and consistency. The `PackageReleaseNotes` field was also reorganized for clarity. [[1]](diffhunk://#diff-47e13a32c0efadc4c63d3a708cf61bfd5175a662505f579f339ec326db947650L40-L49) [[2]](diffhunk://#diff-4e65a88c8f86e709a46c7dbbb5deea46b805c016191a13a541012be5d527f129L39-R51)
* …
=> misc(nuget): Add metadata for NuGet

docs/users-manual/application-otp/how-to-slot-access-codes.md, docs/users-manual/toc.yml
Clarifies documentation on slot access code properties and improves examples. Takes the edits proposed in [PR #263 ](https://github.com/Yubico/Yubico.NET.SDK/pull/263) a step further. 
Local docs build
=> docs: improvements to slot access codes how-to

docs/users-manual/application-piv/private-keys.md, docs/users-manual/application-piv/public-keys.md, docs/users-manual/sdk-programming-guide/pin-complexity-policy.md
Updated remainder of .NET SDK GitHub repo links in documentation to point to `HEAD` branch instead of `develop` or `main`.
=> docs: updated GitHub repo links to point to HEAD branch

Yubico.YubiKey/src/Yubico/YubiKey/Otp/OtpSettings.ExtendedFlags.cs
This pull request updates the documentation for the `UseFastTrigger` method in `OtpSettings.ExtendedFlags.cs` to clarify its behavior and applicability. The summary and remarks now specify that the fast trigger feature is relevant mainly for early model YubiKeys and is enabled by default on current generation devices.
Documentation improvements:
* Clarified the XML documentation for `UseFastTrigger` to indicate it is primarily for backwards compatibility with older YubiKeys, and that the feature is enabled by default on current generation devices. Also clarified that the setting only has an effect when a single slot configuration is written.
=> Suggested documentation changes to UseFastTrigger

Yubico.Core/src/Yubico/PlatformInterop/Libraries.Net47.cs, Yubico.Core/src/Yubico/PlatformInterop/Libraries.cs
This pull request updates preprocessor directives to use `NETFRAMEWORK` instead of `NET47` for conditional compilation. This change helps ensure compatibility with all .NET Framework versions, not just 4.7.
Platform compatibility updates:
* Changed the preprocessor directive from `NET47` to `NETFRAMEWORK` in `Libraries.Net47.cs` to generalize framework targeting.
* Updated the conditional compilation check from `!NET47` to `!NETFRAMEWORK` in `Libraries.cs` for consistency with the new directive.
=> fix(platforminterop): Fix preprocessor directives for code inclusion

docs/users-manual/application-u2f/u2f-pin.md
The U2F docs claimed that YubiKey 5 Series and Security Key Series keys do not have a FIDO2 PIN, which is incorrect. This PR includes the necessary doc corrections plus general improvements to u2f-pin.md.
Local docs build
=> docs: fixed fido2 pin info, general improvements

docs/users-manual/application-fido2/how-fido2-works.md, docs/users-manual/application-u2f/u2f-pin.md
Edited a product name ("YubiKey Security Key Series" -> "Security Key Series") and removed a statement that incorrectly described FIDO U2F behavior.
Local docs build
=> docs: minor edits to U2F and FIDO2 pages
